name: vps


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install ngrok
        run: curl -sL https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip | funzip > ngrok && chmod +x ngrok

      - name: Start tunnel
        run: ./ngrok authtoken ${{ secrets.NGROK_TOKEN }} && ./ngrok http 8080 &
